# Generated by Django 2.0.5 on 2018-06-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('track_id', models.IntegerField()),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=800)),
                ('published', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('image', models.URLField(null=True)),
                ('title', models.CharField(max_length=800, null=True)),
                ('description', models.CharField(max_length=800, null=True)),
                ('site', models.URLField(null=True)),
            ],
        ),
    ]
